/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



package PemesananPT_SBK.VIEW;

import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import PemesananPT_SBK.DAO.Deadline;
import PemesananPT_SBK.DAO.DesainKusen;
import PemesananPT_SBK.DAO.ModelTabel;
import PemesananPT_SBK.DAO.Pesanan;
/**
 *
 * @author ASUS ROG
 */
public class framePemilik extends javax.swing.JFrame {

    /**
     * Creates new form framePemilik1
     */
    public framePemilik() {
        initComponents();
        tanggal_jam_sekarang();
        desainKusenJtable();
        daftarPesananJtable();
        deadLineJtable();
        labelKDDesainKusen.setVisible(false);
        txtKd_DesainKusen.setVisible(false);
        jTextFieldHarga.setText("0");
        txtKDpesanan.setText("");
        txtKDpelanggan.setText("");
        txtKDpelanggan.setVisible(false);
        txtKDpesanan.setVisible(false);

    }

        SimpleDateFormat tahunHariTgl = new SimpleDateFormat("yyyy-MM-dd");

        String[] namaKolom = {"KD Desain Kusen", "Nama Kusen", "Ukuran", "Bahan",
            "Harga"};
        int jmlKolom = namaKolom.length;
        int[] lebar = {150, 300, 50, 100, 400};
        ModelTabel model = new ModelTabel();
        String [][] rs;


        private void desainKusenJtable() {
        DesainKusen dk = new DesainKusen();
        rs = dk.Tampil_Semua_desainKusen() ;
        model.SetTable(jTableDesainKusen, rs, namaKolom, jmlKolom, lebar);
    }

        String[] namaKolom1 = {"KDPsn", "KDPlgn", "NamaPlgn", "NamaKsn", "JmlhKsn",
            "Ukuran", "HrgTotal", "Alamat", "TglPengambilan"};
        int jmlKolom1 = namaKolom1.length;
        int[] lebar1 = {5, 5, 50, 50, 10, 50, 100, 100, 50};



        private void daftarPesananJtable() {
        Pesanan ps = new Pesanan();
        rs = ps.Tampil_Semua_pesanan();
        model.SetTable(tabeldaftarpesanan, rs, namaKolom1, jmlKolom1, lebar1);
    }

        String[] namaKolom2 = { "Nama Pelanggan", "Tgl_Pemesanan","Tgl Pengambilan", "Deadline (Hari)"};
        int jmlKolom2 = namaKolom2.length;
        int[] lebar2 = {100, 50, 50, 50, 50};



        private void deadLineJtable() {
        Deadline dl = new Deadline();
        rs = dl.Tampil_Tanggal_Pengambilan();
        model.SetTable(tableDeadline, rs, namaKolom2, jmlKolom2, lebar2);
    }
    
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnHome1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDeadline = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tglHome = new javax.swing.JLabel();
        jamHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelDaftarDesain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelKDDesainKusen = new javax.swing.JLabel();
        labelUkuranDesain1 = new javax.swing.JLabel();
        labelNamaKusen1 = new javax.swing.JLabel();
        jTextFieldUkuran = new javax.swing.JTextField();
        jTextFieldNamaKusen = new javax.swing.JTextField();
        txtIdPesanan1 = new javax.swing.JLabel();
        jLabelHarga = new javax.swing.JLabel();
        jLabelBahanDesain = new javax.swing.JLabel();
        jTextFieldBahan = new javax.swing.JTextField();
        jTextFieldHarga = new javax.swing.JTextField();
        jButtonTambahDesainKusen = new javax.swing.JButton();
        jButtonEditDesainKusen = new javax.swing.JButton();
        jButtonHapusDesainKusen = new javax.swing.JButton();
        jButtonRefreshDesainKusen = new javax.swing.JButton();
        txtKd_DesainKusen = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDesainKusen = new javax.swing.JTable();
        panelPesanan = new javax.swing.JPanel();
        panelFormPemesanan = new javax.swing.JPanel();
        lbKDpemesanan = new javax.swing.JLabel();
        lbKDpelanggan = new javax.swing.JLabel();
        lbNamaPemesan = new javax.swing.JLabel();
        lbTglPengambilan = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        DateTglPengambilan = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        txtKDpesanan = new javax.swing.JLabel();
        txtKDpelanggan = new javax.swing.JLabel();
        panelDaftarPesanan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeldaftarpesanan = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan PT. SBK");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mainPanel.setBackground(new java.awt.Color(204, 0, 51));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelMenu.setBackground(new java.awt.Color(255, 153, 102));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU");

        btnHome1.setBackground(new java.awt.Color(255, 102, 102));
        btnHome1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-home-60.png"))); // NOI18N
        btnHome1.setText("Home             ");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-gold-bars-60.png"))); // NOI18N
        jButton4.setText("Daftar Desain ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-general-ledger-60.png"))); // NOI18N
        jButton5.setText("Daftar Pesanan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten.setBackground(new java.awt.Color(255, 255, 0));
        panelKonten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelKonten.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kalender Deadline");

        tableDeadline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama_Pelanggan", "Tgl_Pemesanan", "Tgl_Pengambilan", "Deadline (Hari)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDeadline.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableDeadline);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TANGGAL :");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" JAM   :");

        tglHome.setBackground(new java.awt.Color(255, 255, 255));
        tglHome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tglHome.setForeground(new java.awt.Color(255, 255, 255));

        jamHome.setBackground(new java.awt.Color(255, 255, 255));
        jamHome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jamHome.setForeground(new java.awt.Color(255, 255, 255));
        jamHome.setRequestFocusEnabled(false);
        jamHome.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tglHome, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jamHome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglHome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jamHome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/logosbkusen.jpg"))); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelKonten.add(panelHome, "card2");

        panelDaftarDesain.setBackground(new java.awt.Color(255, 102, 102));
        panelDaftarDesain.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Daftar Desain", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 3, true), "Form DesainKusen", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        labelKDDesainKusen.setText("KD DesainKusen");

        labelUkuranDesain1.setText("Ukuran");

        labelNamaKusen1.setText("Nama Kusen");

        jLabelHarga.setText("Harga");

        jLabelBahanDesain.setText("Bahan");

        jTextFieldHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldHargaKeyTyped(evt);
            }
        });

        jButtonTambahDesainKusen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Add.png"))); // NOI18N
        jButtonTambahDesainKusen.setText("Tambah");
        jButtonTambahDesainKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahDesainKusenActionPerformed(evt);
            }
        });

        jButtonEditDesainKusen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Edit-32.png"))); // NOI18N
        jButtonEditDesainKusen.setText("Ubah");
        jButtonEditDesainKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditDesainKusenActionPerformed(evt);
            }
        });

        jButtonHapusDesainKusen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Delete-32.png"))); // NOI18N
        jButtonHapusDesainKusen.setText("Hapus");
        jButtonHapusDesainKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusDesainKusenActionPerformed(evt);
            }
        });

        jButtonRefreshDesainKusen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Refresh-32.png"))); // NOI18N
        jButtonRefreshDesainKusen.setText("Refresh");
        jButtonRefreshDesainKusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshDesainKusenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKDDesainKusen)
                            .addComponent(labelNamaKusen1)
                            .addComponent(labelUkuranDesain1)
                            .addComponent(jLabelBahanDesain))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldBahan, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextFieldUkuran, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtKd_DesainKusen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdPesanan1))
                            .addComponent(jTextFieldNamaKusen)))
                    .addComponent(jLabelHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButtonTambahDesainKusen)
                .addGap(29, 29, 29)
                .addComponent(jButtonEditDesainKusen)
                .addGap(33, 33, 33)
                .addComponent(jButtonHapusDesainKusen)
                .addGap(30, 30, 30)
                .addComponent(jButtonRefreshDesainKusen)
                .addGap(196, 196, 196))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKDDesainKusen)
                    .addComponent(txtIdPesanan1)
                    .addComponent(txtKd_DesainKusen))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNamaKusen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaKusen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelUkuranDesain1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBahanDesain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHarga))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jTextFieldUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTambahDesainKusen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditDesainKusen)
                            .addComponent(jButtonHapusDesainKusen)
                            .addComponent(jButtonRefreshDesainKusen))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTableDesainKusen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KD Desain Kusen", "Nama Kusen", "Ukuran", "Bahan", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDesainKusen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDesainKusenMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableDesainKusen);

        javax.swing.GroupLayout panelDaftarDesainLayout = new javax.swing.GroupLayout(panelDaftarDesain);
        panelDaftarDesain.setLayout(panelDaftarDesainLayout);
        panelDaftarDesainLayout.setHorizontalGroup(
            panelDaftarDesainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarDesainLayout.createSequentialGroup()
                .addGroup(panelDaftarDesainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDaftarDesainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDaftarDesainLayout.setVerticalGroup(
            panelDaftarDesainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarDesainLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelKonten.add(panelDaftarDesain, "card4");

        panelPesanan.setBackground(new java.awt.Color(255, 102, 102));
        panelPesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelFormPemesanan.setBackground(new java.awt.Color(255, 204, 204));
        panelFormPemesanan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Form Pemesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lbKDpemesanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbKDpemesanan.setText("Kode Pesanan");

        lbKDpelanggan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbKDpelanggan.setText("Kode Pelanggan");

        lbNamaPemesan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNamaPemesan.setText("Nama Pelanggan");

        lbTglPengambilan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTglPengambilan.setText("Tgl Pengambilan");

        lbAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAlamat.setText("Alamat");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        txtKDpesanan.setText("jLabel3");

        txtKDpelanggan.setText("jLabel5");

        javax.swing.GroupLayout panelFormPemesananLayout = new javax.swing.GroupLayout(panelFormPemesanan);
        panelFormPemesanan.setLayout(panelFormPemesananLayout);
        panelFormPemesananLayout.setHorizontalGroup(
            panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbKDpelanggan)
                    .addComponent(lbNamaPemesan)
                    .addComponent(lbTglPengambilan)
                    .addComponent(lbAlamat)
                    .addComponent(lbKDpemesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtKDpesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(txtKDpelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DateTglPengambilan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFormPemesananLayout.setVerticalGroup(
            panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKDpemesanan)
                    .addComponent(txtKDpesanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKDpelanggan)
                    .addComponent(txtKDpelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamaPemesan)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTglPengambilan))
                    .addComponent(DateTglPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDaftarPesanan.setBackground(new java.awt.Color(255, 153, 153));
        panelDaftarPesanan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Daftar Pesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        tabeldaftarpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "KD Psn", "KD Plg", "Nama Plg", "Nama Ksn", "Jumlah Ksn", "Ukuran", "Hrg Total", "Alamat", "Tgl Pengambilan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabeldaftarpesanan.getTableHeader().setReorderingAllowed(false);
        tabeldaftarpesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldaftarpesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeldaftarpesanan);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Delete-32.png"))); // NOI18N
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Edit-32.png"))); // NOI18N
        jButton3.setText("Ubah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Refresh-32.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaftarPesananLayout = new javax.swing.GroupLayout(panelDaftarPesanan);
        panelDaftarPesanan.setLayout(panelDaftarPesananLayout);
        panelDaftarPesananLayout.setHorizontalGroup(
            panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarPesananLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDaftarPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDaftarPesananLayout.setVerticalGroup(
            panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarPesananLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDaftarPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout panelPesananLayout = new javax.swing.GroupLayout(panelPesanan);
        panelPesanan.setLayout(panelPesananLayout);
        panelPesananLayout.setHorizontalGroup(
            panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesananLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFormPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDaftarPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(327, 327, 327))
        );
        panelPesananLayout.setVerticalGroup(
            panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFormPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDaftarPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKonten.add(panelPesanan, "card3");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(mainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelHome);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frameUtama n = new frameUtama();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelDaftarDesain);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelPesanan);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void jTextFieldHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldHargaKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_jTextFieldHargaKeyTyped

    private void jButtonTambahDesainKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahDesainKusenActionPerformed
        // TODO add your handling code here:
        DesainKusen dk = new DesainKusen();

        int KD_DesainKusen_dt = 0;
        String Nama_Kusen_dt = jTextFieldNamaKusen.getText().toString();
        String Ukuran_dt = jTextFieldUkuran.getText().toString();
        String Bahan_dt = jTextFieldBahan.getText().toString();
        String harga_dt = jTextFieldHarga.getText().toString();

        int Harga_dt = Integer.parseInt(harga_dt);

        if (jTextFieldNamaKusen.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan nama kusen", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldUkuran.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan ukuran kusen", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldBahan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan bahan kusen", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldHarga.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan harga kusen", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else {
            dk.insert(KD_DesainKusen_dt, Nama_Kusen_dt, Ukuran_dt, Bahan_dt, Harga_dt);
            desainKusenJtable();
            labelKDDesainKusen.setVisible(false);
            txtKd_DesainKusen.setVisible(false);
            jTextFieldNamaKusen.setText("");
            jTextFieldUkuran.setText("");
            jTextFieldBahan.setText("");
            jTextFieldHarga.setText("0");
        }
    }//GEN-LAST:event_jButtonTambahDesainKusenActionPerformed

    private void jButtonEditDesainKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditDesainKusenActionPerformed
        // TODO add your handling code here:
        DesainKusen dk = new DesainKusen();
        String kd_DesainKusen_dt = txtKd_DesainKusen.getText().toString();
        String Nama_Kusen_dt = jTextFieldNamaKusen.getText().toString();
        String Ukuran_dt = jTextFieldUkuran.getText().toString();
        String Bahan_dt = jTextFieldBahan.getText().toString();
        String harga_dt = jTextFieldHarga.getText().toString();

        int KD_DesainKusen_dt = Integer.parseInt(kd_DesainKusen_dt);
        int Harga_dt = Integer.parseInt(harga_dt);

        if (jTextFieldNamaKusen.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan nama kusen", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldUkuran.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukan ukuran", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldBahan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukan bahan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (jTextFieldHarga.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Harap masukkan harga", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else {
            dk.ubah(KD_DesainKusen_dt, Nama_Kusen_dt, Ukuran_dt, Bahan_dt, Harga_dt);
            desainKusenJtable();
            labelKDDesainKusen.setVisible(false);
            txtKd_DesainKusen.setVisible(false);
            jTextFieldNamaKusen.setText("");
            jTextFieldUkuran.setText("");
            jTextFieldBahan.setText("");
            jTextFieldHarga.setText("0");

        }
    }//GEN-LAST:event_jButtonEditDesainKusenActionPerformed

    private void jButtonHapusDesainKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusDesainKusenActionPerformed
        // TODO add your handling code here:
        DesainKusen dk = new DesainKusen();
        String kd_DesainKusen = txtKd_DesainKusen.getText().toString();

        int kd_DesainKusen_dt = Integer.parseInt(kd_DesainKusen);

        dk.hapus(kd_DesainKusen_dt);
        desainKusenJtable();
        labelKDDesainKusen.setVisible(false);
        txtKd_DesainKusen.setVisible(false);
        jTextFieldNamaKusen.setText("");
        jTextFieldUkuran.setText("");
        jTextFieldBahan.setText("");
        jTextFieldHarga.setText("0");
    }//GEN-LAST:event_jButtonHapusDesainKusenActionPerformed

    private void jButtonRefreshDesainKusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshDesainKusenActionPerformed
        // TODO add your handling code here:
        desainKusenJtable();
        labelKDDesainKusen.setVisible(false);
        txtKd_DesainKusen.setVisible(false);
        jTextFieldNamaKusen.setText("");
        jTextFieldUkuran.setText("");
        jTextFieldBahan.setText("");
        jTextFieldHarga.setText("0");
    }//GEN-LAST:event_jButtonRefreshDesainKusenActionPerformed

    private void jTableDesainKusenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDesainKusenMouseClicked
        // TODO add your handling code here:
        int Rows = jTableDesainKusen.getSelectedRow();
        String kd_DesainKusen_dt = jTableDesainKusen.getValueAt(Rows, 0).toString();
        String nama_kusen_dt = jTableDesainKusen.getValueAt(Rows, 1).toString();
        String ukuran_dt = jTableDesainKusen.getValueAt(Rows, 2).toString();
        String bahan_dt = jTableDesainKusen.getValueAt(Rows, 3).toString();
        String harga_dt = jTableDesainKusen.getValueAt(Rows, 4).toString();

        labelKDDesainKusen.setVisible(true);
        txtKd_DesainKusen.setVisible(true);

        txtKd_DesainKusen.setText(kd_DesainKusen_dt);
        jTextFieldNamaKusen.setText(nama_kusen_dt);
        jTextFieldUkuran.setText(ukuran_dt);
        jTextFieldBahan.setText(bahan_dt);
        jTextFieldHarga.setText(harga_dt);

    }//GEN-LAST:event_jTableDesainKusenMouseClicked

    private void tabeldaftarpesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldaftarpesananMouseClicked
        // TODO add your handling code here:
        int Rows = tabeldaftarpesanan.getSelectedRow();
        String kd_pemesanan_dt = tabeldaftarpesanan.getValueAt(Rows, 0).toString();
        String kd_pelanggan_dt = tabeldaftarpesanan.getValueAt(Rows, 1).toString();
        String nama_pelanggan_dt = tabeldaftarpesanan.getValueAt(Rows, 2).toString();
        String tglpengambilan_dt = tabeldaftarpesanan.getValueAt(Rows, 8).toString();
        String alamat_dt = tabeldaftarpesanan.getValueAt(Rows, 7).toString();

        Date tgl_pengambilan_dt = null;
        try {
            tgl_pengambilan_dt = new SimpleDateFormat("yyyy-MM-dd").parse(tglpengambilan_dt);
        } catch (Exception e) {
        }

        txtKDpesanan.setVisible(true);
        txtKDpelanggan.setVisible(true);

        txtKDpesanan.setText(kd_pemesanan_dt);
        txtKDpelanggan.setText(kd_pelanggan_dt);
        txtNamaPelanggan.setText(nama_pelanggan_dt);
        DateTglPengambilan.setDate(tgl_pengambilan_dt);
        txtAlamat.setText(alamat_dt);
    }//GEN-LAST:event_tabeldaftarpesananMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pesanan psn = new Pesanan();
        String kd_pesanan_dt = txtKDpesanan.getText().toString();

        int KD_Pesanan_dt = Integer.parseInt(kd_pesanan_dt);

        psn.hapus(KD_Pesanan_dt);
        daftarPesananJtable();
        txtKDpesanan.setVisible(false);
        txtKDpelanggan.setVisible(false);
        txtNamaPelanggan.setText("");
        DateTglPengambilan.setDate(null);
        txtAlamat.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Pesanan ps = new Pesanan();
        String kd_pemesanan_dt = txtKDpesanan.getText().toString();
        String kd_pelanggan_dt = txtKDpelanggan.getText().toString();
        String Nama_Pelanggan_dt = txtNamaPelanggan.getText().toString();
        Date tglpengambilan_dt = DateTglPengambilan.getDate();
        String Alamat_dt = txtAlamat.getText().toString();

        int KD_Pemesanan_dt = Integer.parseInt(kd_pemesanan_dt);
        int KD_Pelanggan_dt = Integer.parseInt(kd_pelanggan_dt);
        String Tgl_Pengambilan_dt = tahunHariTgl.format(tglpengambilan_dt);

        if (txtKDpesanan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data pesanan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtKDpelanggan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap pilih data pesanan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtNamaPelanggan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukkan nama pelanggan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (DateTglPengambilan.getDate().equals(null)){
            JOptionPane.showMessageDialog(null, "Harap masukkan tgl pengambilan", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukkan alamat", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else {
            ps.ubah(KD_Pemesanan_dt, KD_Pelanggan_dt, Nama_Pelanggan_dt, Tgl_Pengambilan_dt, Alamat_dt);
            daftarPesananJtable();
            txtKDpesanan.setVisible(false);
            txtKDpelanggan.setVisible(false);
            txtNamaPelanggan.setText("");
            DateTglPengambilan.setDate(null);
            txtAlamat.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        daftarPesananJtable();
        txtKDpesanan.setVisible(false);
        txtKDpesanan.setText("");
        txtKDpelanggan.setVisible(false);
        txtKDpesanan.setText("");
        txtNamaPelanggan.setText("");
        DateTglPengambilan.setDate(null);
        txtAlamat.setText("");
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePemilik().setVisible(true);
            }
        });
    }
    
    public void tanggal_jam_sekarang(){
        Thread p = new Thread(){

            public void run (){
            for(;;){
                Calendar cal = new GregorianCalendar();
                int hari = cal.get(Calendar.DAY_OF_MONTH);
                int bulan = cal.get(Calendar.MONTH);
                int tahun = cal.get(Calendar.YEAR);
                tglHome.setText(hari+"-"+(bulan+1)+"-"+tahun);

                int jam = cal.get(Calendar.HOUR);
                int menit = cal.get(Calendar.MINUTE);
                int detik = cal.get(Calendar.SECOND);
                int am_pm = cal.get(Calendar.AM_PM);

                String day_night = "";
                if (am_pm==1) {
                    day_night = "PM";
                }else{
                    day_night = "AM";
                }
                String waktuu = jam + ":" +menit+ ":"+detik+ " " + day_night;
                jamHome.setText(waktuu);

                try {
                    sleep(35);
                } catch (InterruptedException ex) {
                    Logger.getLogger(framePemilik.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        };

       p.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateTglPengambilan;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEditDesainKusen;
    private javax.swing.JButton jButtonHapusDesainKusen;
    private javax.swing.JButton jButtonRefreshDesainKusen;
    private javax.swing.JButton jButtonTambahDesainKusen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBahanDesain;
    private javax.swing.JLabel jLabelHarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableDesainKusen;
    private javax.swing.JTextField jTextFieldBahan;
    private javax.swing.JTextField jTextFieldHarga;
    private javax.swing.JTextField jTextFieldNamaKusen;
    private javax.swing.JTextField jTextFieldUkuran;
    private javax.swing.JLabel jamHome;
    private javax.swing.JLabel labelKDDesainKusen;
    private javax.swing.JLabel labelNamaKusen1;
    private javax.swing.JLabel labelUkuranDesain1;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbKDpelanggan;
    private javax.swing.JLabel lbKDpemesanan;
    private javax.swing.JLabel lbNamaPemesan;
    private javax.swing.JLabel lbTglPengambilan;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelDaftarDesain;
    private javax.swing.JPanel panelDaftarPesanan;
    private javax.swing.JPanel panelFormPemesanan;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPesanan;
    private javax.swing.JTable tabeldaftarpesanan;
    private javax.swing.JTable tableDeadline;
    private javax.swing.JLabel tglHome;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JLabel txtIdPesanan1;
    private javax.swing.JLabel txtKDpelanggan;
    private javax.swing.JLabel txtKDpesanan;
    private javax.swing.JLabel txtKd_DesainKusen;
    private javax.swing.JTextField txtNamaPelanggan;
    // End of variables declaration//GEN-END:variables
}
