/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PemesananPT_SBK.VIEW;

import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import PemesananPT_SBK.DAO.DesainKusen;
import PemesananPT_SBK.DAO.ModelTabel;
import PemesananPT_SBK.DAO.Pelanggan;
import PemesananPT_SBK.DAO.Pesanan;
import java.sql.Connection;
import java.util.GregorianCalendar;
import PemesananPT_SBK.DAO.Koneksi;

/**
 *
 * @author ASUS ROG
 */
public class frameUtama extends javax.swing.JFrame {
    Connection con;
    Statement stat;
    String sql;
    ResultSet rsa;
    

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        daftarPelangganJtable();
        desainKusenJtable();
        tanggal_sekarang();
        lbTampilKDpelanggan.setVisible(false);
        lbTampilNamaPelanggan.setVisible(false);
        lbTampilKDdesain.setVisible(false);
        lbTampilNamaKusen.setVisible(false);
        lbTampilHargaKusen.setVisible(false);
        lbTampilKDpelanggan.setText("0");
        lbTampilNamaPelanggan.setText("");
        lbTampilNamaKusen.setText("");
        lbTampilKDdesain.setText("0");
        lbTampilHargaKusen.setText("0");
        txtJumlahKusen.setText("0");
        txtTotalHarga.setText("0");
        
        //TglPemesanan.setDate(null);
        TglPengambilan.setDate(null);
        
        lbTampilKDpesanan.setVisible(false);
        
        Koneksi DB = new Koneksi();
        DB.KoneksiDatabase();
        con = DB.con;
        stat = DB.stm;
     
    }
    
    
    
    SimpleDateFormat tahunHariTgl = new SimpleDateFormat("yyyy-MM-dd");
    
    String[] namaKolom = {"KD Pelanggan", "Nama Pelanggan", "Alamat"};
        int jmlKolom = namaKolom.length;
        int[] lebar = {150, 150, 150};
        ModelTabel model = new ModelTabel();
        String [][] rs;
        
        
        private void daftarPelangganJtable() {
        Pelanggan pl = new Pelanggan();
        rs = pl.Tampil_Semua_pelanggan();
        model.SetTable(TabelDaftarPelanggan, rs, namaKolom, jmlKolom, lebar);
        }
        
        String[] namaKolom1 = {"KD Kusen", "Nama Kusen", "Ukuran", "Bahan",
            "Harga"};
        int jmlKolom1 = namaKolom1.length;
        int[] lebar1 = {150, 150, 50, 100, 200};
        
        
        private void desainKusenJtable() {
        DesainKusen dk = new DesainKusen();
        rs = dk.Tampil_Semua_desainKusen() ;
        model.SetTable(TabelDesainKusen, rs, namaKolom1, jmlKolom1, lebar);
    }
        
        private void cekAkun () {
        
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        panelMain = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnHome1 = new javax.swing.JButton();
        btnPesanan = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelPesanan = new javax.swing.JPanel();
        panelDaftarPelanggan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelDaftarPelanggan = new javax.swing.JTable();
        panelFormPemesanan = new javax.swing.JPanel();
        lbKDpemesanan = new javax.swing.JLabel();
        lbKDdesainkusen = new javax.swing.JLabel();
        lbNamaKusen = new javax.swing.JLabel();
        lbJumlahKusen = new javax.swing.JLabel();
        lbTotalHarga = new javax.swing.JLabel();
        txtJumlahKusen = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnTambahPemesanan = new javax.swing.JButton();
        btnRefresh1 = new javax.swing.JButton();
        lbNamaPelanggan1 = new javax.swing.JLabel();
        lb_kd_pelanggan1 = new javax.swing.JLabel();
        lbTampilKDpesanan = new javax.swing.JLabel();
        lbTampilKDdesain = new javax.swing.JLabel();
        lbTampilKDpelanggan = new javax.swing.JLabel();
        lbTampilNamaPelanggan = new javax.swing.JLabel();
        lbTampilNamaKusen = new javax.swing.JLabel();
        lbHargaKusen = new javax.swing.JLabel();
        lbTampilHargaKusen = new javax.swing.JLabel();
        lbTglPengambilan = new javax.swing.JLabel();
        TglPengambilan = new com.toedter.calendar.JDateChooser();
        lbTglPemesanan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        Tgl_Pemesanan = new javax.swing.JTextField();
        panelFormPelanggan = new javax.swing.JPanel();
        lbNamaPelanggan = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();
        lbNoTelp = new javax.swing.JLabel();
        txtNoTelpPelanggan = new javax.swing.JTextField();
        lbAlamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatPelanggan = new javax.swing.JTextArea();
        btnTambahPelanggan = new javax.swing.JButton();
        lb_kd_pelanggan = new javax.swing.JLabel();
        txtKdPelanggan = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        panelDesainKusen = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelDesainKusen = new javax.swing.JTable();
        panelLogin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        username_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan PT. SBK");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelMain.setBackground(new java.awt.Color(165, 98, 23));
        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelMenu.setBackground(new java.awt.Color(255, 153, 102));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU");

        btnHome1.setBackground(new java.awt.Color(233, 187, 158));
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-home-60.png"))); // NOI18N
        btnHome1.setText("Home            ");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        btnPesanan.setBackground(new java.awt.Color(233, 187, 158));
        btnPesanan.setForeground(new java.awt.Color(255, 255, 255));
        btnPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-shopping-cart-60.png"))); // NOI18N
        btnPesanan.setText("Pesanan        ");
        btnPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesananActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(233, 187, 158));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/icons8-conference-60.png"))); // NOI18N
        btnLogin.setText("Login Pemilik");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addComponent(btnHome1)
                .addGap(37, 37, 37)
                .addComponent(btnPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten.setBackground(new java.awt.Color(51, 0, 51));
        panelKonten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelKonten.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(226, 155, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/logosbkusen.jpg"))); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        panelKonten.add(panelHome, "card2");

        panelPesanan.setBackground(new java.awt.Color(181, 127, 94));
        panelPesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelDaftarPelanggan.setBackground(new java.awt.Color(226, 155, 104));
        panelDaftarPelanggan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Daftar Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        TabelDaftarPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "KD Pelanggan", "Nama Pelanggan", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDaftarPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDaftarPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelDaftarPelanggan);
        if (TabelDaftarPelanggan.getColumnModel().getColumnCount() > 0) {
            TabelDaftarPelanggan.getColumnModel().getColumn(0).setResizable(false);
            TabelDaftarPelanggan.getColumnModel().getColumn(1).setResizable(false);
            TabelDaftarPelanggan.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout panelDaftarPelangganLayout = new javax.swing.GroupLayout(panelDaftarPelanggan);
        panelDaftarPelanggan.setLayout(panelDaftarPelangganLayout);
        panelDaftarPelangganLayout.setHorizontalGroup(
            panelDaftarPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDaftarPelangganLayout.setVerticalGroup(
            panelDaftarPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelFormPemesanan.setBackground(new java.awt.Color(233, 187, 158));
        panelFormPemesanan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Form Pemesanan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lbKDpemesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbKDpemesanan.setText("Kode Pesanan");

        lbKDdesainkusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbKDdesainkusen.setText("Kode Desain Kusen");

        lbNamaKusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNamaKusen.setText("Nama Kusen");

        lbJumlahKusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbJumlahKusen.setText("Jumlah Kusen");

        lbTotalHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotalHarga.setText("Total Harga");

        txtJumlahKusen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKusenKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKusenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKusenKeyTyped(evt);
            }
        });

        btnTambahPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Add.png"))); // NOI18N
        btnTambahPemesanan.setText("Tambah");
        btnTambahPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPemesananActionPerformed(evt);
            }
        });

        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Refresh-32.png"))); // NOI18N
        btnRefresh1.setText("Refresh");
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        lbNamaPelanggan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNamaPelanggan1.setText("Nama Pelanggan");

        lb_kd_pelanggan1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_kd_pelanggan1.setText("Kode Pelanggan");

        lbTampilKDpesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilKDpesanan.setText("jLabel4");

        lbTampilKDdesain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilKDdesain.setText("jLabel4");

        lbTampilKDpelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilKDpelanggan.setText("jLabel4");

        lbTampilNamaPelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilNamaPelanggan.setText("jLabel4");

        lbTampilNamaKusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilNamaKusen.setText("jLabel4");

        lbHargaKusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHargaKusen.setText("HargaKusen");

        lbTampilHargaKusen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTampilHargaKusen.setText("jLabel4");

        lbTglPengambilan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTglPengambilan.setText("Tanggal Pengambilan");

        lbTglPemesanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTglPemesanan.setText("Tanggal Pemesanan");

        jSeparator1.setEnabled(false);

        Tgl_Pemesanan.setEditable(false);

        javax.swing.GroupLayout panelFormPemesananLayout = new javax.swing.GroupLayout(panelFormPemesanan);
        panelFormPemesanan.setLayout(panelFormPemesananLayout);
        panelFormPemesananLayout.setHorizontalGroup(
            panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbNamaPelanggan1)
                        .addComponent(lb_kd_pelanggan1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPemesananLayout.createSequentialGroup()
                            .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                    .addComponent(lbHargaKusen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTampilHargaKusen))
                                .addComponent(jSeparator3)
                                .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                    .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbKDdesainkusen)
                                        .addComponent(lbNamaKusen)
                                        .addComponent(lbKDpemesanan))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTampilKDdesain, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbTampilNamaKusen, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(268, Short.MAX_VALUE)))
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTampilNamaPelanggan)
                                    .addComponent(lbTampilKDpelanggan)
                                    .addComponent(lbTampilKDpesanan))
                                .addGap(67, 67, 67)
                                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTglPemesanan)
                                    .addComponent(lbTglPengambilan)
                                    .addComponent(TglPengambilan, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(Tgl_Pemesanan)))
                            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                .addComponent(lbJumlahKusen)
                                .addGap(60, 60, 60)
                                .addComponent(txtJumlahKusen, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                        .addComponent(lbTotalHarga)
                                        .addGap(74, 74, 74)
                                        .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPemesananLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTambahPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        panelFormPemesananLayout.setVerticalGroup(
            panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKDpemesanan)
                    .addComponent(lbTampilKDpesanan)
                    .addComponent(lbTglPemesanan))
                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_kd_pelanggan1)
                            .addComponent(lbTampilKDpelanggan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamaPelanggan1)
                            .addComponent(lbTampilNamaPelanggan))
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFormPemesananLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPemesananLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbTampilKDdesain)
                                    .addComponent(lbKDdesainkusen))
                                .addGap(8, 8, 8)))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTampilNamaKusen)
                            .addComponent(lbNamaKusen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTampilHargaKusen)
                            .addComponent(lbHargaKusen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbJumlahKusen)
                            .addComponent(txtJumlahKusen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotalHarga)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(panelFormPemesananLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tgl_Pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTglPengambilan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TglPengambilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelFormPemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        panelFormPelanggan.setBackground(new java.awt.Color(233, 187, 158));
        panelFormPelanggan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Form Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lbNamaPelanggan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNamaPelanggan.setText("Nama Pelanggan");

        txtNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPelangganActionPerformed(evt);
            }
        });

        lbNoTelp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNoTelp.setText("No Telepon");

        txtNoTelpPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpPelangganActionPerformed(evt);
            }
        });
        txtNoTelpPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTelpPelangganKeyTyped(evt);
            }
        });

        lbAlamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAlamat.setText("Alamat");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAlamatPelanggan.setColumns(20);
        txtAlamatPelanggan.setRows(5);
        jScrollPane1.setViewportView(txtAlamatPelanggan);

        btnTambahPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PemesananPT_SBK/PICTURES/Add.png"))); // NOI18N
        btnTambahPelanggan.setText("Tambah");
        btnTambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPelangganActionPerformed(evt);
            }
        });

        lb_kd_pelanggan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_kd_pelanggan.setText("Kode Pelanggan");

        javax.swing.GroupLayout panelFormPelangganLayout = new javax.swing.GroupLayout(panelFormPelanggan);
        panelFormPelanggan.setLayout(panelFormPelangganLayout);
        panelFormPelangganLayout.setHorizontalGroup(
            panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormPelangganLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jSeparator13)
                    .addComponent(jSeparator11)
                    .addComponent(jSeparator10)
                    .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbAlamat)
                        .addGroup(panelFormPelangganLayout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(txtKdPelanggan))
                        .addComponent(lb_kd_pelanggan)
                        .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTambahPelanggan)
                            .addGroup(panelFormPelangganLayout.createSequentialGroup()
                                .addComponent(lbNamaPelanggan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNoTelpPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtNamaPelanggan)))))
                    .addComponent(lbNoTelp, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
        );
        panelFormPelangganLayout.setVerticalGroup(
            panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormPelangganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKdPelanggan)
                .addGap(31, 31, 31)
                .addComponent(lb_kd_pelanggan)
                .addGap(2, 2, 2)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamaPelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNoTelp)
                    .addComponent(txtNoTelpPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFormPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnTambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        panelDesainKusen.setBackground(new java.awt.Color(226, 155, 104));
        panelDesainKusen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Desain Kusen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        TabelDesainKusen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KD Kusen", "Nama_Kusen", "Ukuran", "Bahan", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelDesainKusen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDesainKusenMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelDesainKusen);
        if (TabelDesainKusen.getColumnModel().getColumnCount() > 0) {
            TabelDesainKusen.getColumnModel().getColumn(0).setResizable(false);
            TabelDesainKusen.getColumnModel().getColumn(1).setResizable(false);
            TabelDesainKusen.getColumnModel().getColumn(2).setResizable(false);
            TabelDesainKusen.getColumnModel().getColumn(3).setResizable(false);
            TabelDesainKusen.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelDesainKusenLayout = new javax.swing.GroupLayout(panelDesainKusen);
        panelDesainKusen.setLayout(panelDesainKusenLayout);
        panelDesainKusenLayout.setHorizontalGroup(
            panelDesainKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesainKusenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDesainKusenLayout.setVerticalGroup(
            panelDesainKusenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDesainKusenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPesananLayout = new javax.swing.GroupLayout(panelPesanan);
        panelPesanan.setLayout(panelPesananLayout);
        panelPesananLayout.setHorizontalGroup(
            panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFormPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPesananLayout.createSequentialGroup()
                        .addComponent(panelDaftarPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGroup(panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDesainKusen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFormPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelPesananLayout.setVerticalGroup(
            panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDaftarPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDesainKusen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFormPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(panelFormPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKonten.add(panelPesanan, "card3");

        panelLogin.setBackground(new java.awt.Color(226, 155, 104));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("PT.SBK");

        username_txt.setToolTipText("Username");

        password_txt.setToolTipText("Password");
        password_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_txtKeyPressed(evt);
            }
        });

        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 296, Short.MAX_VALUE))
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel6)
                .addGap(67, 67, 67)
                .addComponent(username_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btLogin)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        panelKonten.add(panelLogin, "card5");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelMain);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelHome);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesananActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelPesanan);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_btnPesananActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        panelKonten.removeAll();
        panelKonten.repaint();
        panelKonten.revalidate();
        //add panel
        panelKonten.add(panelLogin);
        panelKonten.repaint();
        panelKonten.revalidate();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnTambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPelangganActionPerformed
        // TODO add your handling code here:
        Pelanggan pl = new Pelanggan();
        int KD_Pelanggan_dt = 0;
        String Nama_Pelanggan_dt = txtNamaPelanggan.getText().toString();
        String No_Telp_dt = txtNoTelpPelanggan.getText().toString();
        String Alamat_dt = txtAlamatPelanggan.getText().toString();
        

        if (txtNamaPelanggan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan nama anda", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtNoTelpPelanggan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukkan nomor telepon anda", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtAlamatPelanggan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap masukkan alamat anda", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } 
        else {
            pl.insert(KD_Pelanggan_dt, Nama_Pelanggan_dt, No_Telp_dt, Alamat_dt);
            daftarPelangganJtable();
            txtKdPelanggan.setVisible(false);
            txtNamaPelanggan.setText("");
            txtNoTelpPelanggan.setText("");
            txtAlamatPelanggan.setText("");
        }
    }//GEN-LAST:event_btnTambahPelangganActionPerformed

    private void btnTambahPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPemesananActionPerformed
        // TODO add your handling code here:
        Pesanan ps = new Pesanan();
        
        int KD_Pemesanan_dt = 0;
        String KDPelanggan_dt = lbTampilKDpelanggan.getText().toString();
        String KDDesainKusen_dt = lbTampilKDdesain.getText().toString();
        String JumlahKusen_dt = txtJumlahKusen.getText().toString();
        String TotalHarga_dt = txtTotalHarga.getText().toString();
        String TglPemesanan_dt = Tgl_Pemesanan.getText().toString();
        Date TglPengambilan_dt = TglPengambilan.getDate();
         
        //String Tgl_Pemesanan_dt = tahunHariTgl.format(TglPemesanan_dt);
        String Tgl_Pengambilan_dt = tahunHariTgl.format(TglPengambilan_dt);
        int KD_Pelanggan_dt = Integer.parseInt(KDPelanggan_dt);
        int KD_DesainKusen_dt = Integer.parseInt(KDDesainKusen_dt);
        int Harga_Total_dt = Integer.parseInt(TotalHarga_dt);
        int Jumlah_Kusen_dt = Integer.parseInt(JumlahKusen_dt);
        
        
        if (lbTampilKDpelanggan.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data pelanggan terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (lbTampilNamaPelanggan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data pelanggan terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (lbTampilKDdesain.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data desain kusen terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (lbTampilNamaKusen.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data desain kusen terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (lbTampilHargaKusen.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Harap pilih data desain kusen terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (txtJumlahKusen.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Harap masukkan jumlah pesanan desain kusen terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else {
            ps.insert(KD_Pemesanan_dt, KD_Pelanggan_dt, KD_DesainKusen_dt, Jumlah_Kusen_dt, Harga_Total_dt, TglPemesanan_dt, Tgl_Pengambilan_dt);
        
        daftarPelangganJtable();
        desainKusenJtable();
        
        lbTampilKDpelanggan.setVisible(false);
        lbTampilNamaPelanggan.setVisible(false);
        lbTampilKDdesain.setVisible(false);
        lbTampilNamaKusen.setVisible(false);
        lbTampilHargaKusen.setVisible(false);
        lbTampilKDpelanggan.setText("0");
        lbTampilNamaPelanggan.setText("");
        lbTampilNamaKusen.setText("");
        lbTampilKDdesain.setText("0");
        lbTampilHargaKusen.setText("0");
        txtJumlahKusen.setText("0");
        txtTotalHarga.setText("0");
        
       // TglPemesanan.setDate(null);
        TglPengambilan.setDate(null);
        
        lbTampilKDpesanan.setVisible(false);
        }
 
    }//GEN-LAST:event_btnTambahPemesananActionPerformed

    public void FilterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            //Pesan Dialog Boleh Di Hapus Ini Hanya Sebagai Contoh
            JOptionPane.showMessageDialog(null, "Masukan Hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void txtNoTelpPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTelpPelangganKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_txtNoTelpPelangganKeyTyped

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        daftarPelangganJtable();
        desainKusenJtable();
        lbTampilKDpelanggan.setVisible(false);
        lbTampilNamaPelanggan.setVisible(false);
        lbTampilKDdesain.setVisible(false);
        lbTampilNamaKusen.setVisible(false);
        lbTampilHargaKusen.setVisible(false);
        lbTampilKDpelanggan.setText("0");
        lbTampilNamaPelanggan.setText("");
        lbTampilNamaKusen.setText("");
        lbTampilKDdesain.setText("0");
        lbTampilHargaKusen.setText("0");
        txtJumlahKusen.setText("0");
        txtTotalHarga.setText("0");
        
       // TglPemesanan.setDate(null); //bug
        TglPengambilan.setDate(null); //bug
        
        lbTampilKDpesanan.setVisible(false);
        
        txtNamaPelanggan.setText("");
        txtNoTelpPelanggan.setText("");
        txtAlamatPelanggan.setText("");
        
        
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void TabelDaftarPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDaftarPelangganMouseClicked
        // TODO add your handling code here:
        int Rows = TabelDaftarPelanggan.getSelectedRow();
        String kd_pelanggan_dt = TabelDaftarPelanggan.getValueAt(Rows, 0).toString();
        String nama_pelanggan_dt = TabelDaftarPelanggan.getValueAt(Rows, 1).toString();
        
        
        lbTampilKDpelanggan.setVisible(true);
        lbTampilNamaPelanggan.setVisible(true);

        lbTampilKDpelanggan.setText(kd_pelanggan_dt);
        lbTampilNamaPelanggan.setText(nama_pelanggan_dt);
    }//GEN-LAST:event_TabelDaftarPelangganMouseClicked

    private void TabelDesainKusenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDesainKusenMouseClicked
        // TODO add your handling code here:
        int Rows = TabelDesainKusen.getSelectedRow();
        String kd_DesainKusen_dt = TabelDesainKusen.getValueAt(Rows, 0).toString();
        String nama_kusen_dt = TabelDesainKusen.getValueAt(Rows, 1).toString();
        String ukuran_dt = TabelDesainKusen.getValueAt(Rows, 2).toString();
        String bahan_dt = TabelDesainKusen.getValueAt(Rows, 3).toString();
        String harga_dt = TabelDesainKusen.getValueAt(Rows, 4).toString();
        
        
        lbTampilKDdesain.setVisible(true);
        lbTampilNamaKusen.setVisible(true);
        lbTampilHargaKusen.setVisible(true);

        lbTampilKDdesain.setText(kd_DesainKusen_dt);
        lbTampilNamaKusen.setText(bahan_dt);
        lbTampilHargaKusen.setText(harga_dt);
    }//GEN-LAST:event_TabelDesainKusenMouseClicked

    private void txtJumlahKusenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKusenKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
         
    }//GEN-LAST:event_txtJumlahKusenKeyTyped

    private void txtJumlahKusenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKusenKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKusenKeyPressed

    private void txtJumlahKusenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKusenKeyReleased
        // TODO add your handling code here:
        String harga_kusen_dt = lbTampilHargaKusen.getText();
        String jumlah_kusen_dt = txtJumlahKusen.getText();
        
        int jumlah_dt = Integer.parseInt(jumlah_kusen_dt);
        int harga_dt = Integer.parseInt(harga_kusen_dt);
        
        int total_harga_dt = jumlah_dt * harga_dt;
        
        String total_dt = String.valueOf(total_harga_dt);
        
        txtTotalHarga.setText(total_dt);
    }//GEN-LAST:event_txtJumlahKusenKeyReleased

    private void password_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_txtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            btLoginActionPerformed(null);
        }
    }//GEN-LAST:event_password_txtKeyPressed

    private void txtNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPelangganActionPerformed

    private void txtNoTelpPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpPelangganActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        try {
            sql = "SELECT * FROM akun WHERE Username='"+username_txt.getText()+"' AND Password='"+password_txt.getText()+"'";
            rsa = stat.executeQuery(sql);
            if(rsa.next()){
                if(username_txt.getText().equals(rsa.getString("Username")) && password_txt.getText().equals(rsa.getString("Password"))){
                    frameUtama fu = new frameUtama();
                    framePemilik fp = new framePemilik ();
                    fp.setVisible(true);
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Berhasil Login");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password anda salah");
                username_txt.setText("");
                password_txt.setText("");
            }
        } catch (SQLException e) {
            Logger.getLogger(frameUtama.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }
     public void tanggal_sekarang(){
        Thread p = new Thread(){
            
            public void run (){
            for(;;){
                Calendar cal = new GregorianCalendar();
                int hari = cal.get(Calendar.DAY_OF_MONTH);
                int bulan = cal.get(Calendar.MONTH);
                int tahun = cal.get(Calendar.YEAR);
                Tgl_Pemesanan.setText(tahun+"-"+(bulan+1)+"-"+hari);
                
                
                try {
                    sleep(35);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frameUtama.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
            }
        }
        };

       p.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelDaftarPelanggan;
    private javax.swing.JTable TabelDesainKusen;
    private com.toedter.calendar.JDateChooser TglPengambilan;
    private javax.swing.JTextField Tgl_Pemesanan;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPesanan;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnTambahPelanggan;
    private javax.swing.JButton btnTambahPemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbHargaKusen;
    private javax.swing.JLabel lbJumlahKusen;
    private javax.swing.JLabel lbKDdesainkusen;
    private javax.swing.JLabel lbKDpemesanan;
    private javax.swing.JLabel lbNamaKusen;
    private javax.swing.JLabel lbNamaPelanggan;
    private javax.swing.JLabel lbNamaPelanggan1;
    private javax.swing.JLabel lbNoTelp;
    private javax.swing.JLabel lbTampilHargaKusen;
    private javax.swing.JLabel lbTampilKDdesain;
    private javax.swing.JLabel lbTampilKDpelanggan;
    private javax.swing.JLabel lbTampilKDpesanan;
    private javax.swing.JLabel lbTampilNamaKusen;
    private javax.swing.JLabel lbTampilNamaPelanggan;
    private javax.swing.JLabel lbTglPemesanan;
    private javax.swing.JLabel lbTglPengambilan;
    private javax.swing.JLabel lbTotalHarga;
    private javax.swing.JLabel lb_kd_pelanggan;
    private javax.swing.JLabel lb_kd_pelanggan1;
    private javax.swing.JPanel panelDaftarPelanggan;
    private javax.swing.JPanel panelDesainKusen;
    private javax.swing.JPanel panelFormPelanggan;
    private javax.swing.JPanel panelFormPemesanan;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPesanan;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JTextArea txtAlamatPelanggan;
    private javax.swing.JTextField txtJumlahKusen;
    private javax.swing.JLabel txtKdPelanggan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoTelpPelanggan;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField username_txt;
    // End of variables declaration//GEN-END:variables
}
